services:
  - type: web
    name: banker-wingman-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        generateValue: true
      - key: OPENAI_API_KEY
        value: "your-key-here"  # Optional - users provide their own
    scaling:
      minInstances: 1
      maxInstances: 3 